networks:
  nexus.net:
    driver: bridge

services:
  # service api.toubeelib : api pour la prise de rdv
  #
  api.nexus:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - '6080:80'
    volumes:
      - ./api/src:/var/php
    working_dir: /var/php
    networks:
      - nexus.net
    depends_on:
      - nexus.db
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public"

    # service toubiprat.db : base de donn√©es postgresql pour les praticiens

  nexus.db:
    image: 'postgres:latest'
    env_file: ./nexus.env
    ports:
      - '5432:5432'
    networks:
      - nexus.net
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d

  #
  # service administration des bases sql
  #
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - nexus.net

