services:

  # Base de donn√©es PostgreSQL
  db:
    image: postgres:15
    container_name: payment_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - payment_network


  # Interface Adminer
  adminer:
    image: adminer
    container_name: payment_adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - payment_network
    depends_on:
      - db
  # API PHP (Backend)
  api:
    build: ./api
    container_name: payment_api
    restart: always
    environment:
      APP_ENV: ${APP_ENV}
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      API_PUBLIC_URL: ${API_PUBLIC_URL}
    volumes:
      - ./api/src:/var/www/html
      - ./api/logs:/var/log/apache2
    depends_on:
      - db

    ports:
      - "8000:80"
    networks:
      - payment_network


  # Site Web (Frontend)
  web:
    build: ./web
    container_name: payment_web
    restart: always
    environment:
      API_INTERNAL_URL: http://api
      WEB_PUBLIC_URL: ${WEB_PUBLIC_URL}
    volumes:
      - ./web/public:/usr/share/nginx/html
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    ports:
      - "8080:80"
    networks:
      - payment_network


volumes:
  db_data:

networks:
  payment_network:
    driver: bridge
