name: untitled
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  flutter_lints: ^5.0.0
  shared_preferences_android: ^2.2.2
  shared_preferences: ^2.2.2

flutter:

  assets:
    - assets/images/

  uses-material-design: true


flutter_native_splash:
  color: "#AAAAAA"
  image: logo.png
